### ISSUE TITLE
安装依赖的时候报错，怎么解决啊？

### ISSUE THREAD

**Issue by JerroldLee** [xiaokekeT/ourdream#9]
(node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，
1) 安装 .NET Fram
ework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了
其他位置，请将其位置添加到系统
路径中。 [F:\nodejs\React\ourdream\node_modules\bcrypt\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd F:\nodejs\React\ourdream\node_modules\bcrypt
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1

**Comment by coolicer** [comment]
都叫你装Visual C++ 组件了
